name: Event Filters
on: 
  push:
   paths:
    - '*.py'
    - '*.SQL'
    - '*.json'    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: test step
      run: |
         pwd
         echo "${{ github.ref }}"

