name: Event Filters
on: 
  workflow_dispatch:
    inputs:
      image_name:
         description: "Docker Image Name"
         required: true
         default: "nginx"
         type: string 
      app_type:
        type: choice
        options:
        - IOS
        - Windows
        - Linux  
      target_env:
        type: environment      
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: test step
      run: |
         pwd
         echo "${{ inputs.image_name }}"
         echo "${{ inputs.app_type }}"
         echo "${{ secrets.SERVERPASSWD}}"
         echo "${{ secrets.DB_PASSWD}}"

